Repository Jagannath8/shopping, pull requests merged in 2021-07, with the labels that each got.

#8 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DCP'21, Level 2

#24 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: DCP'21, Level 2

#25 About-Us-Page-Created
  aboutus.html
  assets/mission.png
  assets/vision.png
  assets/whychooseus.png
  css/aboutus.css
  css/styles.css
  index.html
Labels: DCP'21, Level 2

#26 Footer added
  css/styles.css
  index.html
Labels: DCP'21, Level 1

#30 Bottom to top scroll button added
  css/styles.css
  index.html
Labels: DCP'21, Level 0

#32 Enhancements
  assets/logo.png
  css/styles.css
  index.html
Labels: DCP'21, Level 1

#33 Changed add to cart button
  index.js
Labels: DCP'21, Level 0

#36 privacy policy added
  index.html
  privacy_policy.html
Labels: DCP'21, Level 1

#39 made socialmedia buttons to connect us
  socialmedia-connect/index.html
  socialmedia-connect/style.css
Labels: DCP'21, Level 1

#40 created a login/signup page
  login or signup/index.html
  login or signup/style.css
Labels: DCP'21, Level 1
